url: "https://leman-th.github.io"
baseurl: ""

title: "Lausanne Event on Machine Learning and Neural Network Theory (LemanTh)"
description: "Official website for the LemanTh event (most recent edition + links to past years)."

plugins: []

include:
  - assets

markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
